default:
  tags:
    - runner-alexis
  cache:
    paths:
      - client/.npm

stages:
  - test
  - build
  - deploy

test-front:
  image: node:lts
  stage: test
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run test
  cache:
    paths:
      - client/node_modules

build-docker:
  image: docker:latest
  stage: build
  script:
    - cd client
    - docker build -t registry.gitlab.com/challengers-g22/my-little-poacher:latest .
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker push registry.gitlab.com/challengers-g22/my-little-poacher:latest
  dependencies:
    - test-front

pages:
  image: node:lts
  stage: build
  only:
    - dev
    - main
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - cp dist/index.html dist/404.html
    - mv dist ../public
  cache:
    paths:
      - client/node_modules
  dependencies:
    - test-front
  artifacts:
    paths:
      - public
