default:
  tags:
    - runner-alexis

stages:
  - test
  - build
  - deploy

pages:
  image: node:lts
  stage: build
  script:
    - cd client
    - npm ci
    - npm run build
    - mv dist ../public
  artifacts:
    paths:
      - public
