default:
  tags:
    - runner-alexis
  cache:
    paths:
      - client/.npm

stages:
  - test
  - build
  - deploy

test-front:
  image: node:lts
  stage: test
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run test
  cache:
    paths:
      - client/node_modules

build-docker:
  image: docker:latest
  stage: build
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: "tcp://docker:2375"
  services:
    - docker:dind
  script:
    - cd client
    - docker build -t 'alexislours/my-little-poacher-front:latest' .
    - docker info
  dependencies:
    - test-front

pages:
  image: node:lts
  stage: build
  only:
    - dev
    - main
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - cp dist/index.html dist/404.html
    - mv dist ../public
  cache:
    paths:
      - client/node_modules
  dependencies:
    - test-front
  artifacts:
    paths:
      - public
