default:
  tags:
    - runner-alexis
  cache:
    paths:
      - client/.npm

stages:
  - test
  - build
  - deploy

test-front:
  image: node:lts
  stage: test
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm rebuild canvas --update-binary
    - npm run test
  cache:
    paths:
      - client/node_modules

build-docker-front:
  image: docker:19.03.0
  stage: build
  only:
    - dev
    - main
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  services:
    - docker:19.03.0-dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - cd client
    - docker build -t 'alexislours/my-little-poacher-front:latest' .
    - docker push 'alexislours/my-little-poacher-front:latest'
  dependencies:
    - test-front

pages:
  image: node:lts
  stage: build
  only:
    - dev
    - main
  script:
    - cd client
    - npm ci --cache .npm --prefer-offline
    - npm run build
    - cp dist/index.html dist/404.html
    - mv dist ../public
  cache:
    paths:
      - client/node_modules
  dependencies:
    - test-front
  artifacts:
    paths:
      - public
